name: Build and publish to ECR

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"

jobs:
  build-publish-image-to-ecr:
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-ecr.yaml
